# Generated by Django 4.1.7 on 2023-04-03 09:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0002_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["-done_mark", "-date"],
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
    ]
