# Generated by Django 4.1.7 on 2023-04-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizer", "0003_alter_task_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={
                "ordering": ["done_mark", "-date"],
                "verbose_name": "task",
                "verbose_name_plural": "tasks",
            },
        ),
        migrations.AlterField(
            model_name="task",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
